changelog_type: 'pull_request' # or 'commit_message'
header_prefix: 'Version:'
commit_changelog: true
comment_changelog: true
# Match Any Pull Request Title by adding this pull_request_title_regex": ".*",
pull_request_title_regex: '^Alpha Release'
version_regex: 'v?([0-9]{1,2})+[.]+([0-9]{1,2})+[.]+([0-9]{1,2})\s\(\d{1,2}-\d{1,2}-\d{4}\)'
group_config:
  - title: Bug Fixes
    labels:
      - defect
  - title: Code Improvements
    labels:
      - accessibility
      - refactor
  - title: New Features
    labels:
      - feature
      - enhancement
  - title: Documentation Updates
    labels:
      - documentation
