import {
  EmptyPackageType,
  PackageType,
  PhaseType,
} from '@digital-ai/dot-components';

// Demo data so that we can provide a constant example.
export const phasesData: Array<PhaseType> = [
  {
    name: 'Build',
    packageVersions: [],
    code_complete: false,
    delivery_category: 'Developing',
    description: '',
  },
  {
    code_complete: true,
    delivery_category: 'Packaged',
    description: '',
    name: 'Acceptance Test',
    packageVersions: [
      {
        _id: '5b60b39a2979935da30f13e1',
        activity_failed: false,
        actual: 62,
        arrival_dt: '2018-07-31T19:08:10.434000',
        cardIndicatorStatus: {
          activity_start_count: 3,
          estimated_time_remaining: 20034751,
          total_activity_count: 11,
        },
        change_count: 45,
        control_failed: false,
        fullversion_from: '5.0.122',
        fullversion_to: '5.0.146',
        last_update_dt: '2018-09-30T05:37:08.084000',
        package_id: '578d26d729799325c58985b4',
        package_name: 'webstore',
        pending_activity: true,
        phase_name: 'Acceptance Test',
        progression_id: '591afccd2979935b172328f8',
        rev_from: 122,
        rev_from_id: '5b9c4fc12979930dbb0f13cd',
        rev_to: 146,
        rev_to_id: '5ba79d5929799324b10f13cf',
        risk_coverage_percentage: null,
        risk_coverage_report_url: null,
        risk_dashboard_url: null,
        risk_failed_tests_count: null,
        risk_failed_tests_report_url: null,
        risk_has_failed_tests: false,
        risk_has_high_risk_file: false,
        risk_has_low_coverage: false,
        risk_has_severity1_violations: false,
        risk_severity1_report_url: null,
        risk_severity1_violation_count: null,
        risk_show_dashboard_link: false,
        team_id: '5bc508902979931838de6218',
        unmanaged_change_count: 0,
        version: '5.0',
        workitem_count: 25,
        workitems: [
          {
            _id: '5b9c4fc12979930dbb0f13c5',
            change_count: 1,
            external_id: 'Story:1243',
            external_key: 'S-01031',
            title: 'Accounting Integration - Spike',
            value_goal: 'improve',
          },
          {
            _id: '5b9d258129799313db0f13cc',
            change_count: 2,
            external_id: 'Story:1244',
            external_key: 'S-01032',
            title: 'Accounting Integration - main',
            value_goal: 'improve',
          },
          {
            _id: '5b9d6e292979931a940f13d3',
            change_count: 3,
            external_id: 'Defect:1268',
            external_key: 'D-01016',
            title: 'Wrong Address on Invoice',
            value_goal: 'maintain',
          },
          {
            _id: '5b9ddfd529799321110f13cc',
            change_count: 2,
            external_id: 'Story:1275',
            external_key: 'S-01041',
            title: 'Remote Customer Lookups',
            value_goal: 'improve',
          },
          {
            _id: '5b9e167129799327790f13d3',
            change_count: 3,
            external_id: 'Story:1282',
            external_key: 'S-01042',
            title: 'Product Overview',
            value_goal: 'improve',
          },
          {
            _id: '5b9edad82979932d250f13d3',
            change_count: 3,
            external_id: 'Story:1231',
            external_key: 'S-01023',
            title: 'View Daily Call Count',
            value_goal: 'improve',
          },
          {
            _id: '5bc76e6c29799334240f13c6',
            change_count: 1,
            external_id: 'Story:1248',
            external_key: 'S-01035',
            title: 'Call Time Reporting',
            value_goal: 'improve',
          },
          {
            _id: '5b9fe1592979933a3b0f13cd',
            change_count: 2,
            external_id: 'Story:1297',
            external_key: 'S-01056',
            title: 'Web Seminars',
            value_goal: 'improve',
          },
          {
            _id: '5ba0633129799340830f13cd',
            change_count: 2,
            external_id: 'Story:1299',
            external_key: 'S-01058',
            title: 'Home Page Updates',
            value_goal: 'improve',
          },
          {
            _id: '5ba09c9e29799347030f13c6',
            change_count: 1,
            external_id: 'Story:1300',
            external_key: 'S-01059',
            title: 'Home Page',
            value_goal: 'improve',
          },
          {
            _id: '5ba101282979934c5f0f13c6',
            change_count: 1,
            external_id: 'Story:1301',
            external_key: 'S-01060',
            title: 'Ship-To Cannot be Updated',
            value_goal: 'improve',
          },
          {
            _id: '5ba189cc29799352790f13c6',
            change_count: 1,
            external_id: 'Story:2104',
            external_key: 'S-01531',
            title: 'Legal Check',
            value_goal: 'improve',
          },
          {
            _id: '5ba2721029799358420f13c6',
            change_count: 1,
            external_id: 'Story:2185',
            external_key: 'S-01532',
            title: 'Rep Avatars',
            value_goal: 'improve',
          },
          {
            _id: '5ba2c7d82979935e780f13c6',
            change_count: 1,
            external_id: 'Story:1232',
            external_key: 'S-01024',
            title: 'Hold Order',
            value_goal: 'improve',
          },
          {
            _id: '5ba3174c29799364440f13cd',
            change_count: 2,
            external_id: 'Story:1238',
            external_key: 'S-01027',
            title: 'Calculate Tax',
            value_goal: 'improve',
          },
          {
            _id: '5ba3bc882979936a2a0f13c6',
            change_count: 1,
            external_id: 'Story:1230',
            external_key: 'S-01022',
            title: 'Add Shipping Notes',
            value_goal: 'improve',
          },
          {
            _id: '5bc76ea7297993703e0f13d5',
            change_count: 3,
            external_id: 'Story:1237',
            external_key: 'S-01026',
            title: "Multiple Ship-To's",
            value_goal: 'improve',
          },
          {
            _id: '5ba5316d29799376410f13d5',
            change_count: 3,
            external_id: 'Story:1241',
            external_key: 'S-01029',
            title: 'Calculate Shipping',
            value_goal: 'improve',
          },
          {
            _id: '5ba56a242979937bba0f13d5',
            change_count: 3,
            external_id: 'Story:1242',
            external_key: 'S-01030',
            title: 'Shipping Notes',
            value_goal: 'improve',
          },
          {
            _id: '5ba64495297993042c0f13ce',
            change_count: 2,
            external_id: 'Story:1227',
            external_key: 'S-01021',
            title: 'Enter RMA',
            value_goal: 'improve',
          },
          {
            _id: '5ba67c982979930abb0f13c7',
            change_count: 1,
            external_id: 'Story:1235',
            external_key: 'S-01025',
            title: 'Update RMA',
            value_goal: 'improve',
          },
          {
            _id: '5ba6bc1c29799310ac0f13d5',
            change_count: 3,
            external_id: 'Story:1240',
            external_key: 'S-01028',
            title: 'Delete RMA',
            value_goal: 'improve',
          },
          {
            _id: '5ba6e95929799317320f13c7',
            change_count: 1,
            external_id: 'Defect:1270',
            external_key: 'D-01018',
            title: 'Icon Background is Wrong Color',
            value_goal: 'maintain',
          },
          {
            _id: '5ba737292979931e770f13c7',
            change_count: 1,
            external_id: 'Story:1494',
            external_key: 'S-01120',
            title:
              'Call Center Soft Pull - Display received data in ping details (within 30 days)',
            value_goal: 'improve',
          },
          {
            _id: '5ba79d5929799324b10f13c7',
            change_count: 1,
            external_id: 'Story:1495',
            external_key: 'S-01121',
            title:
              'Call Center Soft Pull: Hook up Call Center Admin permission to Soft Pull Settings Page Access',
            value_goal: 'improve',
          },
        ],
      },
      {
        package_name: 'empty-app',
      },
      {
        _id: '5b6d3ac4297993664dfa9462',
        activity_failed: false,
        actual: 68,
        arrival_dt: '2018-08-10T07:12:04.239000',
        cardIndicatorStatus: {
          activity_start_count: 3,
          estimated_time_remaining: 6917056,
          total_activity_count: 12,
        },
        change_count: 55,
        control_failed: false,
        fullversion_from: '7.6.95',
        fullversion_to: '7.6.121',
        last_update_dt: '2018-09-20T08:29:01.319000',
        package_id: '578d26e129799325c58985b5',
        package_name: 'database',
        pending_activity: true,
        phase_name: 'Acceptance Test',
        progression_id: '591afccd2979935b172328f8',
        rev_from: 95,
        rev_from_id: '5b91353c2979932d82fa9450',
        rev_to: 121,
        rev_to_id: '5b9fd1db2979934cacfa944a',
        risk_coverage_percentage: null,
        risk_coverage_report_url: null,
        risk_dashboard_url: null,
        risk_failed_tests_count: null,
        risk_failed_tests_report_url: null,
        risk_has_failed_tests: false,
        risk_has_high_risk_file: false,
        risk_has_low_coverage: false,
        risk_has_severity1_violations: false,
        risk_severity1_report_url: null,
        risk_severity1_violation_count: null,
        risk_show_dashboard_link: false,
        team_id: '5bc508902979931838de6218',
        unmanaged_change_count: 3,
        version: '7.6',
        workitem_count: 26,
        workitems: [
          {
            _id: '5b7af4462979937d25fa9440',
            change_count: 3,
            external_id: 'Story:1496',
            external_key: 'S-01122',
            title:
              'Call Center Stand Alone - Print & Message Letter Reprocessing',
            value_goal: 'improve',
          },
          {
            _id: '5b922486297993315efa9450',
            change_count: 3,
            external_id: 'Story:1497',
            external_key: 'S-01123',
            title:
              'Call Center - EqGUIty Pings not being generated for prospects without Call Center event',
            value_goal: 'improve',
          },
          {
            _id: '5b9312a629799336b7fa9442',
            change_count: 1,
            external_id: 'Story:1498',
            external_key: 'S-01124',
            title: 'Call Center Stand Alone - Campaign Manager',
            value_goal: 'improve',
          },
          {
            _id: '5b93a3f52979933c4bfa9442',
            change_count: 1,
            external_id: 'Story:1499',
            external_key: 'S-01125',
            title: 'Call Center Stand Alone and Add On - Employee Dashboard',
            value_goal: 'improve',
          },
          {
            _id: '5b93c9b22979934346fa9449',
            change_count: 2,
            external_id: 'Story:1500',
            external_key: 'S-01126',
            title:
              'Call Center Stand Alone: Design - Conversion of Actions to Events & Activities',
            value_goal: 'improve',
          },
          {
            _id: '5b940a9e2979934991fa9450',
            change_count: 3,
            external_id: 'Story:1501',
            external_key: 'S-01127',
            title:
              'Change Radar Set Up to Drip to Campaigns instead of Actions',
            value_goal: 'improve',
          },
          {
            _id: '5b94a8962979934eddfa9450',
            change_count: 3,
            external_id: 'Story:1502',
            external_key: 'S-01128',
            title:
              'NULLs in the Call Center Rate and Lease Factor for a Call Center will cause issues with Pings',
            value_goal: 'improve',
          },
          {
            _id: '5b94fe9a29799354f7fa9449',
            change_count: 2,
            external_id: 'Story:1503',
            external_key: 'S-01129',
            title: 'Revenue Radar - Select all pings not staying selected',
            value_goal: 'improve',
          },
          {
            _id: '5b959eea2979935ac3fa9449',
            change_count: 2,
            external_id: 'Story:1504',
            external_key: 'S-01130',
            title:
              'Revenue Radar is including old expired pings in the monthly enrollment count and is not enrolling the coCall Centerect total each month',
            value_goal: 'improve',
          },
          {
            _id: '5b963a4d29799360bcfa9443',
            change_count: 1,
            external_id: 'Story:1505',
            external_key: 'S-01131',
            title:
              'Service pings do not show in the mobile app under specific circumstances.',
            value_goal: 'improve',
          },
          {
            _id: '5b96647e2979936711fa944a',
            change_count: 2,
            external_id: 'Story:1506',
            external_key: 'S-01132',
            title:
              'Revenue Radar Multi-Ping Details Icon when accessed through desk log fails to load in Chrome',
            value_goal: 'improve',
          },
          {
            _id: '5b96bf6e2979936d8ffa944a',
            change_count: 2,
            external_id: 'Story:1507',
            external_key: 'S-01133',
            title:
              'BlackBook Process - Exception Arithmetic overflow eCall Centeror converting numeric to data type numeric',
            value_goal: 'improve',
          },
          {
            _id: '5b975a5a2979937318fa9451',
            change_count: 3,
            external_id: 'Story:1508',
            external_key: 'S-01134',
            title:
              "With a certain configuration of settings in Revenue Radar Smart Payment pings have a 0.00% tax rate when they shouldn't.",
            value_goal: 'improve',
          },
          {
            _id: '5b98453229799379bdfa9451',
            change_count: 3,
            external_id: 'Story:1509',
            external_key: 'S-01135',
            title:
              'Ping ROI by Date report including results from outside of date range',
            value_goal: 'improve',
          },
          {
            _id: '5b993fbe2979937f74fa9443',
            change_count: 1,
            external_id: 'Story:1510',
            external_key: 'S-01136',
            title:
              'RevenueRadar Service Tab - Print Documents Icon not working When Selecting Customers With Pings',
            value_goal: 'improve',
          },
          {
            _id: '5b99688629799307f0fa944a',
            change_count: 2,
            external_id: 'Story:1511',
            external_key: 'S-01137',
            title:
              'Call Center Soft Pull: Real Time Ping Generation Default Radar GUI',
            value_goal: 'improve',
          },
          {
            _id: '5b9a179a2979930e9afa944a',
            change_count: 2,
            external_id: 'Story:1512',
            external_key: 'S-01138',
            title:
              'Call Center Soft Pull: Real Time Ping Generation Service Tab GUI',
            value_goal: 'improve',
          },
          {
            _id: '5b9ae4732979931556fa944a',
            change_count: 2,
            external_id: 'Story:1513',
            external_key: 'S-01139',
            title:
              "Revenue Radar - Soft Customer Pull Ping Details page not displaying 'Residual' for a Lease deal",
            value_goal: 'improve',
          },
          {
            _id: '5bc54b112979931af9fa9451',
            change_count: 3,
            external_id: 'Story:1514',
            external_key: 'S-01140',
            title:
              'Soft Customer Pull - Redaction of APR, Payment, Customer Score, and Customer Tier values after 30 days',
            value_goal: 'improve',
          },
          {
            _id: '5b9c1ac229799320a8fa9444',
            change_count: 1,
            external_id: 'Story:1515',
            external_key: 'S-01141',
            title: 'Ping Generation Post Customer Pull',
            value_goal: 'improve',
          },
          {
            _id: '5b9c9a0629799326d6fa944b',
            change_count: 2,
            external_id: 'Story:1516',
            external_key: 'S-01142',
            title: 'Call Center Soft Pull: Testing Ping Live Generation',
            value_goal: 'improve',
          },
          {
            _id: '5b9d1a762979932cd7fa944b',
            change_count: 2,
            external_id: 'Story:1517',
            external_key: 'S-01143',
            title:
              'Call Center Soft Pull: Allow repulls for non-internal server eCall Centeror pulls',
            value_goal: 'improve',
          },
          {
            _id: '5b9e162e2979933365fa9444',
            change_count: 1,
            external_id: 'Story:1518',
            external_key: 'S-01144',
            title:
              'Call Center Soft Pull: Better eCall Centeror messages for non-internal server eCall Centeror pulls',
            value_goal: 'improve',
          },
          {
            _id: '5b9e5b162979933929fa944b',
            change_count: 2,
            external_id: 'Story:1519',
            external_key: 'S-01145',
            title: 'Call Center Soft Pull: Report of Soft Pulls',
            value_goal: 'improve',
          },
          {
            _id: '5b9f75be2979934669fa9452',
            change_count: 3,
            external_id: 'Story:1521',
            external_key: 'S-01147',
            title:
              'Remove exact match on make match in customer portal look me up screen',
            value_goal: 'improve',
          },
          {
            _id: '5b7bc0e2297993054efa9440',
            change_count: 2,
            external_id: 'Story:1522',
            external_key: 'S-01148',
            title:
              'HOL - 500 ECall Centeror (Billing Server - Invalid Subscriber ID) - Desking, Call Center & Service Dashboard Sessions',
            value_goal: 'improve',
          },
        ],
      },
      {
        _id: '59c683b62979936aa8b9ab52',
        activity_failed: false,
        actual: 43,
        arrival_dt: '2017-09-23T15:54:30.566000',
        cardIndicatorStatus: {
          activity_start_count: 3,
          estimated_time_remaining: 20103612,
          total_activity_count: 11,
        },
        change_count: 44,
        control_failed: true,
        fullversion_from: '3.1.83',
        fullversion_to: '3.1.100',
        last_update_dt: '2017-11-01T16:54:32.030000',
        package_id: '578fc04f29799325c589a729',
        package_name: 'api',
        pending_activity: false,
        phase_name: 'Acceptance Test',
        progression_id: '591afccd2979935b172328f8',
        rev_from: 83,
        rev_from_id: '59eb71b129799366ffb9ab50',
        rev_to: 100,
        rev_to_id: '59f4ee832979931690b9ab50',
        risk_coverage_percentage: null,
        risk_coverage_report_url: null,
        risk_dashboard_url: null,
        risk_failed_tests_count: null,
        risk_failed_tests_report_url: null,
        risk_has_failed_tests: false,
        risk_has_high_risk_file: false,
        risk_has_low_coverage: false,
        risk_has_severity1_violations: false,
        risk_severity1_report_url: null,
        risk_severity1_violation_count: null,
        risk_show_dashboard_link: false,
        team_id: '5bc507d029799317d49517fb',
        unmanaged_change_count: 24,
        version: '3.1',
        workitem_count: 8,
        workitems: [
          {
            _id: '59f196572979930319b9ab50',
            change_count: 3,
            external_id: '10299',
            external_key: 'API-100',
            title: 'Install scripts and documentation cleanup',
            value_goal: 'improve',
          },
          {
            _id: '59f248b3297993061cb9ab50',
            change_count: 3,
            external_id: '10298',
            external_key: 'API-99',
            title:
              "UI - Cloud 'Test' button only supports AWS, hide for other providers",
            value_goal: 'maintain',
          },
          {
            _id: '59f2bda72979930921b9ab50',
            change_count: 3,
            external_id: '10297',
            external_key: 'API-98',
            title: '3rd party javascript installs to the wrong location',
            value_goal: 'maintain',
          },
          {
            _id: '59f34e7f2979930c0eb9ab4e',
            change_count: 1,
            external_id: '10296',
            external_key: 'API-97',
            title: 'task engine - new connection and sql exec sybase support',
            value_goal: 'improve',
          },
          {
            _id: '59f3d8132979930eb2b9ab50',
            change_count: 3,
            external_id: '10295',
            external_key: 'API-96',
            title: 'task engine - new connection and sql exec informix support',
            value_goal: 'improve',
          },
          {
            _id: '59f405132979931157b9ab50',
            change_count: 3,
            external_id: '10294',
            external_key: 'API-95',
            title:
              'Remove remnants of deprecated Sybase and Informix connection types.',
            value_goal: 'improve',
          },
          {
            _id: '59f42d6329799313f8b9ab4f',
            change_count: 2,
            external_id: '10293',
            external_key: 'API-94',
            title:
              'UI - User edit dialog able to issue/refresh an API auth token',
            value_goal: 'improve',
          },
          {
            _id: '59f4ee832979931690b9ab4f',
            change_count: 2,
            external_id: '10292',
            external_key: 'API-93',
            title: 'task engine - increase ssh command timeout to 60 seconds',
            value_goal: 'improve',
          },
          {
            _id: '5b7ac99e2979937790fa944e',
            change_count: 3,
            external_id: 'Story:1774',
            external_key: 'S-01400',
            title:
              'Remove the Remove Button from Form Administrator - All EZ Supportships',
            value_goal: 'improve',
          },
          {
            _id: '5b7af4462979937d25fa9440',
            change_count: 3,
            external_id: 'Story:1496',
            external_key: 'S-01122',
            title:
              'Call Center Stand Alone - Print & Message Letter Reprocessing',
            value_goal: 'improve',
          },
          {
            _id: '5b7bc0e2297993054efa9440',
            change_count: 2,
            external_id: 'Story:1522',
            external_key: 'S-01148',
            title:
              'HOL - 500 ECall Centeror (Billing Server - Invalid Subscriber ID) - Desking, Call Center & Service Dashboard Sessions',
            value_goal: 'improve',
          },
        ],
      },
      {
        _id: '59fcd04a29799335e22ae843',
        activity_failed: false,
        actual: 68,
        arrival_dt: '2017-11-03T20:23:37.984000',
        cardIndicatorStatus: {
          activity_start_count: 7,
          estimated_time_remaining: 1895319,
          total_activity_count: 11,
        },
        change_count: 24,
        control_failed: true,
        fullversion_from: '3.1.69',
        fullversion_to: '3.1.82',
        last_update_dt: '2017-11-01T16:54:32.030000',
        package_id: '578fc04f29799325c589a729',
        package_name: 'api',
        pending_activity: false,
        phase_name: 'Regression Test',
        progression_id: '591afccd2979935b172328f8',
        rev_from: 69,
        rev_from_id: '59d638a32979933824b9ab4f',
        rev_to: 82,
        rev_to_id: '59df2e002979935bfbb9ab50',
        risk_coverage_percentage: null,
        risk_coverage_report_url: null,
        risk_dashboard_url: null,
        risk_failed_tests_count: null,
        risk_failed_tests_report_url: null,
        risk_has_failed_tests: false,
        risk_has_high_risk_file: false,
        risk_has_low_coverage: false,
        risk_has_severity1_violations: false,
        risk_severity1_report_url: null,
        risk_severity1_violation_count: null,
        risk_show_dashboard_link: false,
        team_id: '5bc507d029799317d49517fb',
        unmanaged_change_count: 0,
        version: '3.1',
        workitem_count: 14,
        workitems: [
          {
            _id: '59d638a32979933824b9ab4e',
            change_count: 1,
            external_id: '10286',
            external_key: 'API-87',
            title: 'Cato Vcenter Integration',
            value_goal: 'improve',
          },
          {
            _id: '59d71a932979933b53b9ab4e',
            change_count: 1,
            external_id: '10291',
            external_key: 'API-92',
            title: 'Datastore update large data',
            value_goal: 'improve',
          },
          {
            _id: '59d805e32979933e4bb9ab4e',
            change_count: 1,
            external_id: '10290',
            external_key: 'API-91',
            title:
              'tak engine - vcloud api commands extended to include vapp management commands',
            value_goal: 'improve',
          },
          {
            _id: '59d8daef29799340d8b9ab4f',
            change_count: 2,
            external_id: '10289',
            external_key: 'API-90',
            title: 'task engine - http command should support cookie use',
            value_goal: 'improve',
          },
          {
            _id: '59d9c51329799343b6b9ab4e',
            change_count: 1,
            external_id: '10288',
            external_key: 'API-89',
            title: 'System Requirements for Cato',
            value_goal: 'improve',
          },
          {
            _id: '59da969b297993464ab9ab4f',
            change_count: 2,
            external_id: '10287',
            external_key: 'API-88',
            title: 'Cato Dashboard Login Issue',
            value_goal: 'improve',
          },
          {
            _id: '59db916329799348e0b9ab4e',
            change_count: 1,
            external_id: '10285',
            external_key: 'API-86',
            title: 'Cato Aws Integration',
            value_goal: 'improve',
          },
          {
            _id: '59dc45632979934b7eb9ab4f',
            change_count: 2,
            external_id: '10284',
            external_key: 'API-85',
            title: 'datastore - group, aggregate, and function capabilities',
            value_goal: 'improve',
          },
          {
            _id: '59dc89d32979934e74b9ab4f',
            change_count: 2,
            external_id: '10283',
            external_key: 'API-84',
            title:
              'task engine - new connection error when using an asset with a shared credential that uses a private key',
            value_goal: 'improve',
          },
          {
            _id: '59dcc3f32979935148b9ab4f',
            change_count: 2,
            external_id: '10282',
            external_key: 'API-83',
            title:
              'Task engine - update winrm code to use latest pywinrm library',
            value_goal: 'improve',
          },
          {
            _id: '59dd8eeb29799353e4b9ab50',
            change_count: 3,
            external_id: '10281',
            external_key: 'API-82',
            title: 'Cato Uninstallation',
            value_goal: 'improve',
          },
          {
            _id: '59de68e32979935689b9ab4f',
            change_count: 2,
            external_id: '10280',
            external_key: 'API-81',
            title:
              'shared credential page - attempting to delete a shared credential that is in use on asset displays no message',
            value_goal: 'improve',
          },
          {
            _id: '59dee06b297993591fb9ab4f',
            change_count: 2,
            external_id: '10279',
            external_key: 'API-80',
            title:
              'Task engine - new connection ssh fails with must be string or buffer, not None is a password is prompted but no password is defined',
            value_goal: 'improve',
          },
          {
            _id: '59df2e002979935bfbb9ab4f',
            change_count: 2,
            external_id: '10278',
            external_key: 'API-79',
            title:
              'task engine - new connection ssh sometimes does not delete the temp private key if command errors',
            value_goal: 'improve',
          },
        ],
      },
    ] as Array<PackageType | EmptyPackageType>,
  },
  {
    code_complete: false,
    delivery_category: 'Packaged',
    description: '',
    name: 'Performance Test',
    packageVersions: [
      {
        _id: '5bb0610429799307ee4df016',
        activity_failed: false,
        actual: 89,
        arrival_dt: '2018-09-30T05:37:08.084000',
        cardIndicatorStatus: {
          activity_start_count: 9,
          estimated_time_remaining: 17986529,
          total_activity_count: 11,
        },
        change_count: 54,
        control_failed: false,
        fullversion_from: '5.0.62',
        fullversion_to: '5.0.89',
        last_update_dt: '2018-09-30T05:37:08.084000',
        package_id: '578d26d729799325c58985b4',
        package_name: 'webstore',
        pending_activity: true,
        phase_name: 'Performance Test',
        progression_id: '591afccd2979935b172328f8',
        rev_from: 62,
        rev_from_id: '5b60b39a2979935da30f13d4',
        rev_to: 89,
        rev_to_id: '5b70e26929799305cc0f13c6',
        risk_coverage_percentage: null,
        risk_coverage_report_url: null,
        risk_dashboard_url: null,
        risk_failed_tests_count: null,
        risk_failed_tests_report_url: null,
        risk_has_failed_tests: false,
        risk_has_high_risk_file: false,
        risk_has_low_coverage: false,
        risk_has_severity1_violations: false,
        risk_severity1_report_url: null,
        risk_severity1_violation_count: null,
        risk_show_dashboard_link: false,
        team_id: '5bc508902979931838de6218',
        unmanaged_change_count: 1,
        version: '5.0',
        workitem_count: 28,
        workitems: [
          {
            _id: '5b60b3982979935da30f13ca',
            change_count: 3,
            external_id: 'Story:1797',
            external_key: 'S-01423',
            title:
              'Form Designer - Additional Merge Tags - Loan to Value Desking Object',
            value_goal: 'improve',
          },
          {
            _id: '5b61924029799364260f13bc',
            change_count: 1,
            external_id: 'Story:1798',
            external_key: 'S-01424',
            title: 'iSiteId parameter missing a value in Revenue Aging report',
            value_goal: 'improve',
          },
          {
            _id: '5b61e1f12979936abf0f13c3',
            change_count: 2,
            external_id: 'Story:1799',
            external_key: 'S-01425',
            title: 'Code snippet to pull advisor photo needed',
            value_goal: 'improve',
          },
          {
            _id: '5b62c76529799370a60f13bc',
            change_count: 1,
            external_id: 'Story:1800',
            external_key: 'S-01426',
            title: 'DMS Op Code Import Integration: Warn if not time value',
            value_goal: 'improve',
          },
          {
            _id: '5b636a4929799376c40f13bc',
            change_count: 1,
            external_id: 'Story:1801',
            external_key: 'S-01427',
            title:
              'Resource Scheduling ENH: Tooltip on Hours to show resource assigned',
            value_goal: 'improve',
          },
          {
            _id: '5b63f0d02979937c2b0f13bc',
            change_count: 1,
            external_id: 'Story:1802',
            external_key: 'S-01428',
            title:
              'DMS Op Code Import Integration: Ability to edit op code details in list view',
            value_goal: 'improve',
          },
          {
            _id: '5b64125429799303b40f13ca',
            change_count: 3,
            external_id: 'Story:1803',
            external_key: 'S-01429',
            title: 'Implement Skill Set Scheduling Logic in Mobile Garage',
            value_goal: 'improve',
          },
          {
            _id: '5b64eb5d2979930ac90f13c3',
            change_count: 2,
            external_id: 'Story:1804',
            external_key: 'S-01430',
            title: 'Leverage Click-to-Call for Service event contacts - mobile',
            value_goal: 'improve',
          },
          {
            _id: '5b6555c429799310e70f13ca',
            change_count: 3,
            external_id: 'Story:1805',
            external_key: 'S-01431',
            title: 'Present customer information during appointment workflow',
            value_goal: 'improve',
          },
          {
            _id: '5b65c2fe29799317390f13c4',
            change_count: 2,
            external_id: 'Story:1806',
            external_key: 'S-01432',
            title: 'Call Center - Need access to Call Center service history',
            value_goal: 'improve',
          },
          {
            _id: '5b6618112979931d5a0f13bd',
            change_count: 1,
            external_id: 'Story:1807',
            external_key: 'S-01433',
            title:
              'Integrated Op Code Import Tool: Need to consume ADP import file',
            value_goal: 'improve',
          },
          {
            _id: '5b665d71297993241f0f13cb',
            change_count: 3,
            external_id: 'Story:1808',
            external_key: 'S-01434',
            title:
              'Integrated Op Code Import Tool: Need to consume Siri export file',
            value_goal: 'improve',
          },
          {
            _id: '5b671ff829799329cd0f13bd',
            change_count: 1,
            external_id: 'Story:1809',
            external_key: 'S-01435',
            title:
              'Integrated Op Code Import Tool: Need a search/sort/select facility',
            value_goal: 'improve',
          },
          {
            _id: '5b67f45029799330040f13bd',
            change_count: 1,
            external_id: 'Story:1810',
            external_key: 'S-01436',
            title:
              'Integrated Op Code Import Tool: Need to consume EZ SupportTrack export file',
            value_goal: 'improve',
          },
          {
            _id: '5b68c8a929799336490f13c4',
            change_count: 2,
            external_id: 'Story:1811',
            external_key: 'S-01437',
            title: 'Integrated Import Op Code Admin Tool',
            value_goal: 'improve',
          },
          {
            _id: '5b69bb012979933c330f13bd',
            change_count: 1,
            external_id: 'Story:1812',
            external_key: 'S-01438',
            title:
              'Customer Portal: Responsive screens down to phone - The Rest',
            value_goal: 'improve',
          },
          {
            _id: '5b6a66cc29799342120f13bd',
            change_count: 1,
            external_id: 'Story:1813',
            external_key: 'S-01439',
            title:
              'Customer Portal: Responsive screens down to phone - landing page only',
            value_goal: 'improve',
          },
          {
            _id: '5b6a90c029799347d30f13c4',
            change_count: 2,
            external_id: 'Story:1814',
            external_key: 'S-01440',
            title:
              'Add texting option to confirmation/reminder prompt in mobile service',
            value_goal: 'improve',
          },
          {
            _id: '5b6aea482979934e110f13cb',
            change_count: 3,
            external_id: 'Story:1815',
            external_key: 'S-01441',
            title: 'Implement op code image admin window',
            value_goal: 'improve',
          },
          {
            _id: '5b6bcced297993540e0f13be',
            change_count: 1,
            external_id: 'Story:1816',
            external_key: 'S-01442',
            title:
              'Implement service manager alert for new packages added for recommended factory packages',
            value_goal: 'improve',
          },
          {
            _id: '5b6c546429799359db0f13cc',
            change_count: 3,
            external_id: 'Story:1817',
            external_key: 'S-01443',
            title:
              'Add new image selection screen for op codes to op code admin screen',
            value_goal: 'improve',
          },
          {
            _id: '5b6cecbc2979935fd90f13cc',
            change_count: 3,
            external_id: 'Story:1818',
            external_key: 'S-01444',
            title:
              'Compile images to be used for op codes shown on customer portal',
            value_goal: 'improve',
          },
          {
            _id: '5b6d5c4d297993664d0f13c5',
            change_count: 2,
            external_id: 'Story:1819',
            external_key: 'S-01445',
            title: 'Call Center Global Call Center Monitor Report',
            value_goal: 'improve',
          },
          {
            _id: '5b6e4c892979936c330f13be',
            change_count: 1,
            external_id: 'Story:1820',
            external_key: 'S-01446',
            title:
              'Forms BGUIlt with Forms Designer Appear in Printable Forms - Mobile App',
            value_goal: 'improve',
          },
          {
            _id: '5b6ef766297993728c0f13c5',
            change_count: 2,
            external_id: 'Story:1821',
            external_key: 'S-01447',
            title: 'Printing PDF Forms - Print a PDF form - Mobile App',
            value_goal: 'improve',
          },
          {
            _id: '5b6fca5529799378050f13cc',
            change_count: 3,
            external_id: 'Story:1822',
            external_key: 'S-01448',
            title: 'Forms and Bundles - Save to Work Notes - Mobile App',
            value_goal: 'improve',
          },
          {
            _id: '5b706b1d2979937e5a0f13be',
            change_count: 1,
            external_id: 'Story:1823',
            external_key: 'S-01449',
            title: 'Bundles Appears in Printable Forms Dropdown - Mobile App',
            value_goal: 'improve',
          },
          {
            _id: '5b70e26929799305cc0f13be',
            change_count: 1,
            external_id: 'Story:1824',
            external_key: 'S-01450',
            title: 'Print a Bundle- Mobile App',
            value_goal: 'improve',
          },
        ],
      },
      {
        _id: '5b83ce712979931838dea456',
        activity_failed: false,
        actual: 44,
        arrival_dt: '2018-08-27T10:12:01.325000',
        cardIndicatorStatus: {
          activity_start_count: 9,
          estimated_time_remaining: 4222084,
          total_activity_count: 12,
        },
        change_count: 48,
        control_failed: false,
        fullversion_from: '7.5.45',
        fullversion_to: '7.5.67',
        last_update_dt: '2018-09-25T16:22:01.235000',
        package_id: '578d26e129799325c58985b5',
        package_name: 'database',
        pending_activity: true,
        phase_name: 'Performance Test',
        progression_id: '591afccd2979935b172328f8',
        rev_from: 45,
        rev_from_id: '5b53f67c2979933dabfa9442',
        rev_to: 67,
        rev_to_id: '5b61ea5b2979934295fa944c',
        risk_coverage_percentage: null,
        risk_coverage_report_url: null,
        risk_dashboard_url: null,
        risk_failed_tests_count: null,
        risk_failed_tests_report_url: null,
        risk_has_failed_tests: false,
        risk_has_high_risk_file: false,
        risk_has_low_coverage: false,
        risk_has_severity1_violations: false,
        risk_severity1_report_url: null,
        risk_severity1_violation_count: null,
        risk_show_dashboard_link: false,
        team_id: '5bc508902979931838de6218',
        unmanaged_change_count: 0,
        version: '7.5',
        workitem_count: 23,
        workitems: [
          {
            _id: '5b53f67c2979933dabfa943a',
            change_count: 1,
            external_id: 'Story:1825',
            external_key: 'S-01451',
            title:
              'Next Gen Call Center Call Center Charges Calculation Not Matching - Outlet Rental Car Call Center',
            value_goal: 'improve',
          },
          {
            _id: '5b54147a2979933fe2fa9448',
            change_count: 3,
            external_id: 'Story:1826',
            external_key: 'S-01452',
            title:
              'Automation: Research & Design Ability to add/remove users from the queue',
            value_goal: 'improve',
          },
          {
            _id: '5b548cf22979934573fa943a',
            change_count: 1,
            external_id: 'Story:1827',
            external_key: 'S-01453',
            title: 'Automation: Config - Multiple Point Support',
            value_goal: 'improve',
          },
          {
            _id: '5b5570862979934b57fa9441',
            change_count: 2,
            external_id: 'Story:1828',
            external_key: 'S-01454',
            title:
              'Printable Forms: For Desklog need a pop-up version of Form Selection screen',
            value_goal: 'improve',
          },
          {
            _id: '5b55a84e2979935194fa943a',
            change_count: 1,
            external_id: 'Story:1829',
            external_key: 'S-01455',
            title: 'Billion DCJR EZ SupportTrack identifier in Desking',
            value_goal: 'improve',
          },
          {
            _id: '5b56046a29799357affa9448',
            change_count: 3,
            external_id: 'Story:1830',
            external_key: 'S-01456',
            title: 'Forms: Print Form Selection Modal in Desking',
            value_goal: 'improve',
          },
          {
            _id: '5b5638ea2979935d53fa9448',
            change_count: 3,
            external_id: 'Story:1831',
            external_key: 'S-01457',
            title:
              'Not able to edit existing Call Center events from the unconverted ups screen',
            value_goal: 'improve',
          },
          {
            _id: '5b56ee8e2979936337fa9448',
            change_count: 3,
            external_id: 'Story:1832',
            external_key: 'S-01458',
            title: 'Desking Trim Label Change',
            value_goal: 'improve',
          },
          {
            _id: '5b57c1052979936a42fa943a',
            change_count: 1,
            external_id: 'Story:1833',
            external_key: 'S-01459',
            title:
              'Contact Dashboard to Desking when changing Call Center - Cap Cost issue - Global',
            value_goal: 'improve',
          },
          {
            _id: '5b58714629799370e0fa9449',
            change_count: 3,
            external_id: 'Story:1834',
            external_key: 'S-01460',
            title: 'Desking: misrepresentation of Cap Reduction Tax?',
            value_goal: 'improve',
          },
          {
            _id: '5b594a122979937731fa9449',
            change_count: 3,
            external_id: 'Story:1835',
            external_key: 'S-01461',
            title:
              'Desking changes a field coming from the VIN decode to an empty string',
            value_goal: 'improve',
          },
          {
            _id: '5b5a24462979937cccfa9442',
            change_count: 2,
            external_id: 'Story:1836',
            external_key: 'S-01462',
            title: 'Marketing display more indicator if  60',
            value_goal: 'improve',
          },
          {
            _id: '5b5afa7e2979930439fa9442',
            change_count: 2,
            external_id: 'Story:1837',
            external_key: 'S-01463',
            title: 'Call Center List - EZ Supportship Filter Enterprise Only',
            value_goal: 'improve',
          },
          {
            _id: '5b5b547e2979930aebfa9442',
            change_count: 2,
            external_id: 'Story:1838',
            external_key: 'S-01464',
            title: 'Customer - Notification ribbon',
            value_goal: 'improve',
          },
          {
            _id: '5b5c1d5a29799310f9fa9449',
            change_count: 3,
            external_id: 'Story:1839',
            external_key: 'S-01465',
            title: 'Loyalty Tab - Enterprise View',
            value_goal: 'improve',
          },
          {
            _id: '5b5d0fee2979931663fa9442',
            change_count: 2,
            external_id: 'Story:1840',
            external_key: 'S-01466',
            title:
              'On the Fly Tracking Code Creation for ListbGUIlder Message Blasts',
            value_goal: 'improve',
          },
          {
            _id: '5b5d7c722979931d25fa943b',
            change_count: 1,
            external_id: 'Story:1841',
            external_key: 'S-01467',
            title: 'Data Warehouse - Calendar 13',
            value_goal: 'improve',
          },
          {
            _id: '5b5e24ba29799322abfa9442',
            change_count: 2,
            external_id: 'Story:1842',
            external_key: 'S-01468',
            title: 'Data Warehouse - cd_cont.aspx 25',
            value_goal: 'improve',
          },
          {
            _id: '5bc549322979932920fa943b',
            change_count: 1,
            external_id: 'Story:1843',
            external_key: 'S-01469',
            title: 'Data Warehouse - cd_event_list.aspx 22',
            value_goal: 'improve',
          },
          {
            _id: '5b5f80112979933050fa943c',
            change_count: 1,
            external_id: 'Story:1844',
            external_key: 'S-01470',
            title: 'Data Warehouse - cd_event_todo_list.aspx 21',
            value_goal: 'improve',
          },
          {
            _id: '5b602a77297993368afa944a',
            change_count: 3,
            external_id: 'Story:1845',
            external_key: 'S-01471',
            title: 'Data Warehouse - View History 20',
            value_goal: 'improve',
          },
          {
            _id: '5b6115c62979933c70fa944a',
            change_count: 3,
            external_id: 'Story:1846',
            external_key: 'S-01472',
            title: 'Data Warehouse - New Co-Buyer 24',
            value_goal: 'improve',
          },
          {
            _id: '5b61ea5a2979934295fa9443',
            change_count: 2,
            external_id: 'Story:1847',
            external_key: 'S-01473',
            title: 'Data Warehouse - Customer Trades 16',
            value_goal: 'improve',
          },
        ],
      },
      {
        _id: '59f9fc4829799335e22ae905',
        activity_failed: false,
        actual: 68,
        arrival_dt: '2017-11-01T16:54:32.030000',
        cardIndicatorStatus: {
          activity_start_count: 9,
          estimated_time_remaining: 1158539,
          total_activity_count: 11,
        },
        change_count: 50,
        control_failed: true,
        fullversion_from: '3.1.43',
        fullversion_to: '3.1.68',
        last_update_dt: '2017-11-01T16:54:32.030000',
        package_id: '578fc04f29799325c589a729',
        package_name: 'api',
        pending_activity: false,
        phase_name: 'Performance Test',
        progression_id: '591afccd2979935b172328f8',
        rev_from: 43,
        rev_from_id: '59c683b62979936aa8b9ab50',
        rev_to: 68,
        rev_to_id: '59d37d072979932ffdb9ab4f',
        risk_coverage_percentage: null,
        risk_coverage_report_url: null,
        risk_dashboard_url: null,
        risk_failed_tests_count: null,
        risk_failed_tests_report_url: null,
        risk_has_failed_tests: false,
        risk_has_high_risk_file: false,
        risk_has_low_coverage: false,
        risk_has_severity1_violations: false,
        risk_severity1_report_url: null,
        risk_severity1_violation_count: null,
        risk_show_dashboard_link: false,
        team_id: '5bc507d029799317d49517fb',
        unmanaged_change_count: 0,
        version: '3.1',
        workitem_count: 26,
        workitems: [
          {
            _id: '59c683b62979936aa8b9ab4f',
            change_count: 2,
            external_id: '10267',
            external_key: 'API-68',
            title: 'Ssh Into instance failed',
            value_goal: 'improve',
          },
          {
            _id: '59c6fd1b2979936d43b9ab50',
            change_count: 3,
            external_id: '10277',
            external_key: 'API-78',
            title: 'Commands with field arrays crash the task editor.',
            value_goal: 'improve',
          },
          {
            _id: '59c7c813297993707fb9ab4e',
            change_count: 1,
            external_id: '10276',
            external_key: 'API-77',
            title: 'task engine, create an s3 copy file command',
            value_goal: 'improve',
          },
          {
            _id: '59c86af72979937375b9ab4f',
            change_count: 2,
            external_id: '10275',
            external_key: 'API-76',
            title: 'Step Templates - better handling of changes to the xml',
            value_goal: 'improve',
          },
          {
            _id: '59c8c263297993764cb9ab50',
            change_count: 3,
            external_id: '10274',
            external_key: 'API-75',
            title: 'Test Cloud Connection - sometimes shows a misleading error',
            value_goal: 'improve',
          },
          {
            _id: '59c9b31729799378efb9ab4f',
            change_count: 2,
            external_id: '10273',
            external_key: 'API-74',
            title: 'PLACEHOLDER - reuse',
            value_goal: 'improve',
          },
          {
            _id: '59ca3a172979937b8bb9ab4e',
            change_count: 1,
            external_id: '10272',
            external_key: 'API-73',
            title: 'Cato Cloud Discovery BAD request',
            value_goal: 'improve',
          },
          {
            _id: '59cb0aeb2979937e19b9ab4f',
            change_count: 2,
            external_id: '10271',
            external_key: 'API-72',
            title:
              'Launch an Instance in a subnet in a VPC with a particular Security Group in AWS',
            value_goal: 'improve',
          },
          {
            _id: '59cb2bf729799301e0b9ab50',
            change_count: 3,
            external_id: '10270',
            external_key: 'API-71',
            title: 'AWS Cloud Formation',
            value_goal: 'improve',
          },
          {
            _id: '59cba127297993051ab9ab50',
            change_count: 3,
            external_id: '10269',
            external_key: 'API-70',
            title:
              'default ports - change all default ports to live in the 808x range instead of the 400x range',
            value_goal: 'improve',
          },
          {
            _id: '59cc27eb2979930855b9ab4f',
            change_count: 2,
            external_id: '10268',
            external_key: 'API-69',
            title: 'VPC Creation Failed',
            value_goal: 'improve',
          },
          {
            _id: '59ccccaf2979930ae5b9ab4e',
            change_count: 1,
            external_id: '10266',
            external_key: 'API-67',
            title: 'Sql Exec - results as dictionary (oracle, sqlserver)',
            value_goal: 'improve',
          },
          {
            _id: '59cd1f6b2979930d7ab9ab4f',
            change_count: 2,
            external_id: '10265',
            external_key: 'API-66',
            title:
              "Ability to disable 'legacy' variable replacement on a per-task basis.",
            value_goal: 'improve',
          },
          {
            _id: '59cd4a4f2979931011b9ab4e',
            change_count: 1,
            external_id: '10264',
            external_key: 'API-65',
            title:
              'Task Engine - log file show codeblock/step instead of useless step_id',
            value_goal: 'improve',
          },
          {
            _id: '59ce24bf29799312e3b9ab4f',
            change_count: 2,
            external_id: '10263',
            external_key: 'API-64',
            title:
              'task editor, send email command fields are too narrow, widen',
            value_goal: 'improve',
          },
          {
            _id: '59ceab472979931585b9ab4f',
            change_count: 2,
            external_id: '10262',
            external_key: 'API-63',
            title:
              'command line tools - should accept -T<token> as an argument in lieu of key/secretkey',
            value_goal: 'improve',
          },
          {
            _id: '59cf16272979931819b9ab4f',
            change_count: 2,
            external_id: '10261',
            external_key: 'API-62',
            title: 'asset edit, local credentials not saving to asest',
            value_goal: 'improve',
          },
          {
            _id: '59cfa0e72979931aabb9ab50',
            change_count: 3,
            external_id: '10260',
            external_key: 'API-61',
            title:
              'admin security log overlays settings page but is transparent',
            value_goal: 'improve',
          },
          {
            _id: '59d069ff2979931d5eb9ab4f',
            change_count: 2,
            external_id: '10259',
            external_key: 'API-60',
            title:
              'Set Variable - make Value box wider, below the value and modifier',
            value_goal: 'improve',
          },
          {
            _id: '59d0d1d32979932039b9ab4e',
            change_count: 1,
            external_id: '10258',
            external_key: 'API-59',
            title:
              "API Call command - make user optional, support 'token' auth",
            value_goal: 'improve',
          },
          {
            _id: '59d13b8729799322c8b9ab4f',
            change_count: 2,
            external_id: '10257',
            external_key: 'API-58',
            title: 'HTTP Command - result variable',
            value_goal: 'improve',
          },
          {
            _id: '59d210572979932563b9ab4f',
            change_count: 2,
            external_id: '10256',
            external_key: 'API-57',
            title: 'API - command to export ALL tasks, not just one',
            value_goal: 'improve',
          },
          {
            _id: '59d238e329799327f8b9ab4e',
            change_count: 1,
            external_id: '10255',
            external_key: 'API-56',
            title: 'Task Loop command - counter variables now case sensitive',
            value_goal: 'improve',
          },
          {
            _id: '59d25f8f2979932a85b9ab50',
            change_count: 3,
            external_id: '10254',
            external_key: 'API-55',
            title: "Task Engine - 'telnet' support for connections",
            value_goal: 'improve',
          },
          {
            _id: '59d348c32979932d68b9ab4e',
            change_count: 1,
            external_id: '10253',
            external_key: 'API-54',
            title: 'SqlAnywhere connections - port parameter',
            value_goal: 'improve',
          },
          {
            _id: '59d37d072979932ffdb9ab4e',
            change_count: 1,
            external_id: '10252',
            external_key: 'API-53',
            title: 'Task codeblock naming now case sensitive',
            value_goal: 'improve',
          },
        ],
      },
    ],
  },
  {
    code_complete: false,
    delivery_category: 'Packaged',
    description: '',
    name: 'Ready for Delivery',
    packageVersions: [
      {
        _id: '5b95e2ac29799307ee4ded3e',
        activity_failed: false,
        actual: 33,
        arrival_dt: '2018-09-10T03:19:08.070000',
        cardIndicatorStatus: {
          activity_start_count: 11,
          estimated_time_remaining: 11399998,
          total_activity_count: 11,
        },
        change_count: 53,
        control_failed: false,
        fullversion_from: '4.8.1',
        fullversion_to: '4.8.61',
        last_update_dt: '2018-10-02T06:27:08.074000',
        package_id: '578d26d729799325c58985b4',
        package_name: 'webstore',
        pending_activity: true,
        phase_name: 'Ready for Delivery',
        progression_id: '591afccd2979935b172328f8',
        rev_from: 34,
        rev_from_id: '5b48a2592979931dd40f13c8',
        rev_to: 61,
        rev_to_id: '5b58a89d297993455b0f13c4',
        risk_coverage_percentage: 39,
        risk_coverage_report_url:
          'http://dtp.parasoft.acme.demo:8089/grs/dtp/explorers/coverage?buildId=PARABANK3-20180510&coverageIndex=0&filterId=3',
        risk_dashboard_url:
          'http://dtp.parasoft.acme.demo:8089/grs/dtp/dashboards/1?filterId=3&period=10drops&baselineBuild=firstBuildInPeriod&targetBuild=buildId:PARABANK3-20180510',
        risk_failed_tests_count: 4,
        risk_failed_tests_report_url:
          'http://dtp.parasoft.acme.demo:8089/grs/dtp/explorers/test?buildId=PARABANK3-20180510&coverageIndex=0&filterId=3&status=fail',
        risk_has_failed_tests: true,
        risk_has_high_risk_file: false,
        risk_has_low_coverage: true,
        risk_has_severity1_violations: true,
        risk_severity1_report_url:
          'http://dtp.parasoft.acme.demo:8089/grs/dtp/explorers/violations?buildId=PARABANK3-20180510&filterId=3&severity=1',
        risk_severity1_violation_count: 1,
        risk_show_dashboard_link: true,
        team_id: '5bc508902979931838de6218',
        unmanaged_change_count: 2,
        version: '4.8',
        workitem_count: 27,
        workitems: [
          {
            _id: '5b48a2582979931dd40f13bf',
            change_count: 2,
            external_id: 'Story:1207',
            external_key: 'S-01001',
            title: 'Logon',
            value_goal: 'improve',
          },
          {
            _id: '5b496120297993242b0f13bf',
            change_count: 2,
            external_id: 'Story:1212',
            external_key: 'S-01006',
            title: 'Logoff',
            value_goal: 'improve',
          },
          {
            _id: '5b49a7702979932a440f13bf',
            change_count: 2,
            external_id: 'Story:1215',
            external_key: 'S-01009',
            title: 'Update Member',
            value_goal: 'improve',
          },
          {
            _id: '5b49fcfc29799330500f13c6',
            change_count: 3,
            external_id: 'Story:1208',
            external_key: 'S-01002',
            title: 'Add Customer Details',
            value_goal: 'improve',
          },
          {
            _id: '5bc76b9d29799336ab0f13c7',
            change_count: 3,
            external_id: 'Story:1209',
            external_key: 'S-01003',
            title: 'Add Customer Header',
            value_goal: 'improve',
          },
          {
            _id: '5b4a80f12979933c5d0f13b9',
            change_count: 1,
            external_id: 'Story:1211',
            external_key: 'S-01005',
            title: 'Edit Customer',
            value_goal: 'improve',
          },
          {
            _id: '5b4b57a0297993427d0f13c0',
            change_count: 2,
            external_id: 'Story:1216',
            external_key: 'S-01010',
            title: 'View Call Count',
            value_goal: 'improve',
          },
          {
            _id: '5b4c508829799348cb0f13c7',
            change_count: 3,
            external_id: 'Story:1219',
            external_key: 'S-01013',
            title: 'Customer List',
            value_goal: 'improve',
          },
          {
            _id: '5b4c97512979934f440f13c0',
            change_count: 2,
            external_id: 'Story:1222',
            external_key: 'S-01016',
            title: 'Order List by Day',
            value_goal: 'improve',
          },
          {
            _id: '5b4cbba429799355140f13c0',
            change_count: 2,
            external_id: 'Story:1217',
            external_key: 'S-01011',
            title: 'Add Multiple Lines',
            value_goal: 'improve',
          },
          {
            _id: '5b4d93bc2979935b640f13c0',
            change_count: 2,
            external_id: 'Story:1218',
            external_key: 'S-01012',
            title: 'Add Order Header',
            value_goal: 'improve',
          },
          {
            _id: '5b4e7d6829799361320f13b9',
            change_count: 1,
            external_id: 'Story:1220',
            external_key: 'S-01014',
            title: 'Add Order Line',
            value_goal: 'improve',
          },
          {
            _id: '5b4ee2e429799367090f13b9',
            change_count: 1,
            external_id: 'Story:1221',
            external_key: 'S-01015',
            title: 'Enter Order Total',
            value_goal: 'improve',
          },
          {
            _id: '5b4fb7002979936d020f13b9',
            change_count: 1,
            external_id: 'Story:1224',
            external_key: 'S-01018',
            title: 'Link Order to Customer',
            value_goal: 'improve',
          },
          {
            _id: '5bc76bd729799372df0f13c8',
            change_count: 3,
            external_id: 'Story:1226',
            external_key: 'S-01020',
            title: 'Ship Order',
            value_goal: 'improve',
          },
          {
            _id: '5b503c9929799378dc0f13ba',
            change_count: 1,
            external_id: 'Story:1223',
            external_key: 'S-01017',
            title: 'Answer Call - Customer',
            value_goal: 'improve',
          },
          {
            _id: '5b51199d2979937f680f13ba',
            change_count: 1,
            external_id: 'Defect:1256',
            external_key: 'D-01007',
            title: 'Bad Part Number Allowed',
            value_goal: 'maintain',
          },
          {
            _id: '5b51800929799307af0f13ba',
            change_count: 1,
            external_id: 'Defect:1257',
            external_key: 'D-01008',
            title: 'Order Summary Includes Cancellations',
            value_goal: 'maintain',
          },
          {
            _id: '5b5259882979930d8d0f13c1',
            change_count: 2,
            external_id: 'Defect:1260',
            external_key: 'D-01009',
            title: 'Pick List Reversed',
            value_goal: 'maintain',
          },
          {
            _id: '5b5316ac29799313c80f13c8',
            change_count: 3,
            external_id: 'Defect:1263',
            external_key: 'D-01012',
            title: 'Canadian Addresses - bad formatting',
            value_goal: 'maintain',
          },
          {
            _id: '5b5361e82979931a400f13ba',
            change_count: 1,
            external_id: 'Story:1225',
            external_key: 'S-01019',
            title: 'Order Status Check',
            value_goal: 'improve',
          },
          {
            _id: '5b542434297993208a0f13c1',
            change_count: 2,
            external_id: 'Story:2339',
            external_key: 'S-01534',
            title: 'Filter for call manager.',
            value_goal: 'improve',
          },
          {
            _id: '5b550d2c297993267f0f13c1',
            change_count: 2,
            external_id: 'Story:2340',
            external_key: 'S-01535',
            title: 'Hover on calls',
            value_goal: 'improve',
          },
          {
            _id: '5b55d2492979932ce70f13c1',
            change_count: 2,
            external_id: 'Story:2341',
            external_key: 'S-01536',
            title: 'Dashboard Paging',
            value_goal: 'improve',
          },
          {
            _id: '5bc76c1529799332f80f13c2',
            change_count: 2,
            external_id: 'Story:2342',
            external_key: 'S-01537',
            title: 'Account Status Icon',
            value_goal: 'improve',
          },
          {
            _id: '5b57222429799338c30f13c9',
            change_count: 3,
            external_id: 'Story:2343',
            external_key: 'S-01538',
            title: 'Contact Info Lookup',
            value_goal: 'improve',
          },
          {
            _id: '5b57cc882979933f6c0f13bb',
            change_count: 1,
            external_id: 'Story:2344',
            external_key: 'S-01539',
            title: 'Contact Create in CRM',
            value_goal: 'improve',
          },
        ],
      },
      {
        _id: '5baa60a92979931838dea7b9',
        activity_failed: false,
        actual: 44,
        arrival_dt: '2018-09-25T16:22:01.235000',
        cardIndicatorStatus: {
          activity_start_count: 12,
          estimated_time_remaining: 1868588,
          total_activity_count: 12,
        },
        change_count: 41,
        control_failed: false,
        fullversion_from: '7.5.25',
        fullversion_to: '7.5.44',
        last_update_dt: '2018-09-25T16:22:01.235000',
        package_id: '578d26e129799325c58985b5',
        package_name: 'database',
        pending_activity: true,
        phase_name: 'Ready for Delivery',
        progression_id: '591afccd2979935b172328f8',
        rev_from: 25,
        rev_from_id: '5b4102372979932addfa9447',
        rev_to: 44,
        rev_to_id: '5b4a4ec52979931ff2fa9451',
        risk_coverage_percentage: null,
        risk_coverage_report_url: null,
        risk_dashboard_url: null,
        risk_failed_tests_count: null,
        risk_failed_tests_report_url: null,
        risk_has_failed_tests: false,
        risk_has_high_risk_file: false,
        risk_has_low_coverage: false,
        risk_has_severity1_violations: false,
        risk_severity1_report_url: null,
        risk_severity1_violation_count: null,
        risk_show_dashboard_link: false,
        team_id: '5bc508902979931838de6218',
        unmanaged_change_count: 0,
        version: '7.5',
        workitem_count: 20,
        workitems: [
          {
            _id: '5b4102362979932addfa943e',
            change_count: 2,
            external_id: 'Story:2345',
            external_key: 'S-01540',
            title: 'Notify Rep',
            value_goal: 'improve',
          },
          {
            _id: '5b41d59e2979932f26fa943e',
            change_count: 2,
            external_id: 'Story:2346',
            external_key: 'S-01541',
            title: 'Create Defect',
            value_goal: 'improve',
          },
          {
            _id: '5b41fae229799334bcfa943e',
            change_count: 2,
            external_id: 'Story:2348',
            external_key: 'S-01542',
            title: 'Status Hover for linked defects',
            value_goal: 'improve',
          },
          {
            _id: '5b429ab92979933a6dfa9437',
            change_count: 1,
            external_id: 'Defect:1236',
            external_key: 'D-01004',
            title: 'Export Missing ID Column',
            value_goal: 'maintain',
          },
          {
            _id: '5b42cd1e2979934094fa9445',
            change_count: 3,
            external_id: 'Defect:1261',
            external_key: 'D-01010',
            title: 'VAT Not Always Applied',
            value_goal: 'maintain',
          },
          {
            _id: '5b43988e2979934652fa943e',
            change_count: 2,
            external_id: 'Story:1289',
            external_key: 'S-01048',
            title: 'Contact Us',
            value_goal: 'improve',
          },
          {
            _id: '5b43c89b2979934cebfa943e',
            change_count: 2,
            external_id: 'Story:1290',
            external_key: 'S-01049',
            title: 'Product Descriptions',
            value_goal: 'improve',
          },
          {
            _id: '5b441e262979935229fa9445',
            change_count: 3,
            external_id: 'Story:1531',
            external_key: 'S-01157',
            title:
              'Avoid POST exception thrown for certain inventory units when loading',
            value_goal: 'improve',
          },
          {
            _id: '5b44bc1e2979935851fa9445',
            change_count: 3,
            external_id: 'Story:1532',
            external_key: 'S-01158',
            title:
              'Call Center Direct Post Service and parts leads do not generate new service lead',
            value_goal: 'improve',
          },
          {
            _id: '5b4531122979935f28fa943f',
            change_count: 2,
            external_id: 'Story:1533',
            external_key: 'S-01159',
            title:
              'GU – Guam is missing from the State dropdown in the Mobile Call Center App.',
            value_goal: 'improve',
          },
          {
            _id: '5b4557be2979936544fa943f',
            change_count: 2,
            external_id: 'Story:1534',
            external_key: 'S-01160',
            title: 'Automation: Convert a test to script',
            value_goal: 'improve',
          },
          {
            _id: '5b45b1be2979936bbefa9438',
            change_count: 1,
            external_id: 'Story:1535',
            external_key: 'S-01161',
            title: 'Automation: Refresh frequency',
            value_goal: 'improve',
          },
          {
            _id: '5b461bad29799371befa9438',
            change_count: 1,
            external_id: 'Story:1536',
            external_key: 'S-01162',
            title: 'Automation: Ability to add/remove users from the queue',
            value_goal: 'improve',
          },
          {
            _id: '5b46d98729799378f3fa9438',
            change_count: 1,
            external_id: 'Story:1537',
            external_key: 'S-01163',
            title:
              'Automation: Access Automation within Call Center Mobile app',
            value_goal: 'improve',
          },
          {
            _id: '5b47975e2979937e58fa9438',
            change_count: 1,
            external_id: 'Story:1538',
            external_key: 'S-01164',
            title: 'IL Taxes calculating incorrectly',
            value_goal: 'improve',
          },
          {
            _id: '5b47e1aa2979930547fa9438',
            change_count: 1,
            external_id: 'Story:1539',
            external_key: 'S-01165',
            title: 'Next Gen Call Center Charges Calculation Not Matching',
            value_goal: 'improve',
          },
          {
            _id: '5b4854fa2979930c17fa9446',
            change_count: 3,
            external_id: 'Story:1540',
            external_key: 'S-01166',
            title: 'Forms - Site Spinner - Chrome Only',
            value_goal: 'improve',
          },
          {
            _id: '5b4908fa2979931242fa9446',
            change_count: 3,
            external_id: 'Story:1541',
            external_key: 'S-01167',
            title: 'User is able to print forms from event summary window',
            value_goal: 'improve',
          },
          {
            _id: '5b49ecca297993186ffa9446',
            change_count: 3,
            external_id: 'Story:1542',
            external_key: 'S-01168',
            title: 'Appointment Scheduler in Service Dashboard',
            value_goal: 'improve',
          },
          {
            _id: '5b4a4ec22979931ff2fa9447',
            change_count: 3,
            external_id: 'Story:1543',
            external_key: 'S-01169',
            title: 'Ability to sort appointments by assigned resource',
            value_goal: 'improve',
          },
        ],
      },
      {
        _id: '59eb202429799335e22ae887',
        activity_failed: false,
        actual: 19,
        arrival_dt: '2017-10-21T10:23:32.033000',
        cardIndicatorStatus: {
          activity_start_count: 11,
          estimated_time_remaining: 1127905,
          total_activity_count: 11,
        },
        change_count: 43,
        control_failed: true,
        fullversion_from: '3.0.1',
        fullversion_to: '3.0.42',
        last_update_dt: '2017-11-02T03:35:32.029000',
        package_id: '578fc04f29799325c589a729',
        package_name: 'api',
        pending_activity: false,
        phase_name: 'Ready for Delivery',
        progression_id: '591afccd2979935b172328f8',
        rev_from: 21,
        rev_from_id: '59b512db297993306cb9ab50',
        rev_to: 42,
        rev_to_id: '59fccee02979936459b9ab50',
        risk_coverage_percentage: null,
        risk_coverage_report_url: null,
        risk_dashboard_url: null,
        risk_failed_tests_count: null,
        risk_failed_tests_report_url: null,
        risk_has_failed_tests: false,
        risk_has_high_risk_file: false,
        risk_has_low_coverage: false,
        risk_has_severity1_violations: false,
        risk_severity1_report_url: null,
        risk_severity1_violation_count: null,
        risk_show_dashboard_link: false,
        team_id: '5bc507d029799317d49517fb',
        unmanaged_change_count: 0,
        version: '3.0',
        workitem_count: 22,
        workitems: [
          {
            _id: '59b512db297993306cb9ab4f',
            change_count: 2,
            external_id: '10231',
            external_key: 'API-32',
            title:
              'Move task editor flow control commands under control category to distinguish them from Flow task commands',
            value_goal: 'improve',
          },
          {
            _id: '59b5d3472979933303b9ab50',
            change_count: 3,
            external_id: '10230',
            external_key: 'API-31',
            title:
              'winrm new connection, test for initial connection and sleep and retry multiple times on timeout',
            value_goal: 'improve',
          },
          {
            _id: '59b65123297993354eb9ab4e',
            change_count: 1,
            external_id: '10229',
            external_key: 'API-30',
            title:
              'winrm command should issue a message to the log prior to execution for long running commands',
            value_goal: 'improve',
          },
          {
            _id: '59b6cfb329799337b0b9ab4e',
            change_count: 1,
            external_id: '10228',
            external_key: 'API-29',
            title:
              'Change task command documentation label from Cato docs to ClearCode docs',
            value_goal: 'improve',
          },
          {
            _id: '59fcce6829799339f1b9ab4f',
            change_count: 2,
            external_id: '10227',
            external_key: 'API-28',
            title:
              'task engine, create a new random integer generator function with floor and ceiling parameters',
            value_goal: 'improve',
          },
          {
            _id: '59b826972979933c83b9ab4e',
            change_count: 1,
            external_id: '10226',
            external_key: 'API-27',
            title: "Messenger isn't honoring the 'off' setting.",
            value_goal: 'improve',
          },
          {
            _id: '59b8ecdf2979933eccb9ab4e',
            change_count: 1,
            external_id: '10225',
            external_key: 'API-26',
            title: 'Change Log on Cloud and Cloud Account edit pages.',
            value_goal: 'improve',
          },
          {
            _id: '59b90b93297993411db9ab4f',
            change_count: 2,
            external_id: '10224',
            external_key: 'API-25',
            title: 'Add cloud account edit support for Azure cloud services',
            value_goal: 'improve',
          },
          {
            _id: '59b9309b2979934364b9ab50',
            change_count: 3,
            external_id: '10223',
            external_key: 'API-24',
            title:
              'New task command to support starting and stopping vms in Azure cloud',
            value_goal: 'improve',
          },
          {
            _id: '59ba10e729799345b6b9ab4f',
            change_count: 2,
            external_id: '10222',
            external_key: 'API-23',
            title:
              "Task Run Log isn't updating dynamically on messaging, or doesn't always display the last message.",
            value_goal: 'improve',
          },
          {
            _id: '59baa1852979934845b9ab50',
            change_count: 3,
            external_id: '10221',
            external_key: 'API-22',
            title:
              'Task engine variable processing enters an infinite loop when attempting to replace variable with certain bad syntax',
            value_goal: 'improve',
          },
          {
            _id: '59bb759f2979934a39b9ab50',
            change_count: 3,
            external_id: '10220',
            external_key: 'API-21',
            title:
              'VersionOne Extension - Implement API connect, query, get, and post commands.',
            value_goal: 'improve',
          },
          {
            _id: '59bc225b2979934cecb9ab50',
            change_count: 3,
            external_id: '10219',
            external_key: 'API-20',
            title:
              "Scheduler setting CleanAppRegistry is implemented and doesn't do anything.  Fix, or remove the setting.",
            value_goal: 'improve',
          },
          {
            _id: '59bd05b32979934f6db9ab4f',
            change_count: 2,
            external_id: '10218',
            external_key: 'API-19',
            title: "Scheduler 'MaxDays' setting is not implemented",
            value_goal: 'improve',
          },
          {
            _id: '59bd512b29799351d8b9ab50',
            change_count: 3,
            external_id: '10217',
            external_key: 'API-18',
            title:
              'Task  SQL Exec As Dictionary option does not work for SQL Server/Oracle.',
            value_goal: 'improve',
          },
          {
            _id: '59bd9d572979935491b9ab4f',
            change_count: 2,
            external_id: '10216',
            external_key: 'API-17',
            title: 'Ability to add the variable stack to the task run log.',
            value_goal: 'improve',
          },
          {
            _id: '59be68132979935736b9ab4f',
            change_count: 2,
            external_id: '10215',
            external_key: 'API-16',
            title:
              'Flow extension to Initiate a Pipeline instead of an HTTP command',
            value_goal: 'improve',
          },
          {
            _id: '59be87f329799359c5b9ab4e',
            change_count: 1,
            external_id: '10214',
            external_key: 'API-15',
            title:
              "New Flow extension to read values from a PI Group's globals.",
            value_goal: 'improve',
          },
          {
            _id: '59bed05f2979935c52b9ab4e',
            change_count: 1,
            external_id: '10213',
            external_key: 'API-14',
            title:
              'Winrm error on vm startup, connection refused error should be retried',
            value_goal: 'improve',
          },
          {
            _id: '59bf3a8b2979935ed7b9ab4e',
            change_count: 1,
            external_id: '10212',
            external_key: 'API-13',
            title:
              'Exporting certain tasks as json then importing back in fouls up structure of task',
            value_goal: 'improve',
          },
          {
            _id: '59bfaacf29799361c2b9ab4f',
            change_count: 2,
            external_id: '10211',
            external_key: 'API-12',
            title: 'Task Activity Log page enabled for websockets messaging.',
            value_goal: 'improve',
          },
          {
            _id: '59fccee02979936459b9ab4f',
            change_count: 2,
            external_id: '10210',
            external_key: 'API-11',
            title:
              'Automate Facelift - update pages to feel like the rest of the UI',
            value_goal: 'improve',
          },
        ],
      },
    ],
  },
  {
    code_complete: false,
    delivery_category: 'Packaged',
    description: '',
    name: 'Canary Release',
    packageVersions: [],
  },
];
