import { ApplicationAPI } from '../ProgressionBoardInterfaces';

export const sampleApplicationAPIData: ApplicationAPI = {
  sourceControls: [
    {
      id: '111111',
      title: 'GitLab',
      servers: [
        {
          id: '111111111111111111111111',
          title: 'Gitlab - Server 1',
          isdefault: false,
          name: 'Configuration/Custom/Configuration111',
          team_id: null,
          token: '',
          url: 'https://about.gitlab.com/',
        },
        {
          id: '111111111111111111111112',
          title: 'Gitlab - Server 2',
          isdefault: false,
          name: 'Configuration/Custom/Configuration112',
          team_id: null,
          token: '',
          url: 'https://about.gitlab.com/',
        },
        {
          id: '111111111111111111111113',
          title: 'Gitlab - Server 3',
          isdefault: false,
          name: 'Configuration/Custom/Configuration113',
          team_id: null,
          token: '',
          url: 'https://about.gitlab.com/',
        },
      ],
    },
    {
      id: '22222',
      title: 'GitHub',
      servers: [
        {
          id: '111111111111111111111121',
          title: 'GitHub - Server 1',
          isdefault: false,
          name: 'Configuration/Custom/Configuration121',
          owner: 'TODO',
          team_id: null,
          token: '',
          url: 'https://github.com',
        },
        {
          id: '111111111111111111111122',
          title: 'GitHub - Server 2',
          isdefault: false,
          name: 'Configuration/Custom/Configuration122',
          owner: 'TODO',
          team_id: null,
          token: '',
          url: 'https://github.com',
        },
        {
          id: '111111111111111111111123',
          title: 'GitHub - Server 3',
          isdefault: false,
          name: 'Configuration/Custom/Configuration123',
          owner: 'TODO',
          team_id: null,
          token: '',
          url: 'https://github.com',
        },
        {
          id: '111111111111111111111124',
          title: 'GitHub - Server 4',
          isdefault: false,
          name: 'Configuration/Custom/Configuration124',
          owner: 'TODO',
          team_id: null,
          token: '',
          url: 'https://github.com',
        },
      ],
    },
  ],
  ticketSystems: [
    {
      id: '12121212',
      title: 'Jiraplugin',
      servers: [
        {
          id: '222222222222222222222221',
          title: 'Jira Server 1',
          improve_types: '',
          isdefault: false,
          maintain_types: '',
          name: 'Configuration/Custom/Configuration2221',
          password: '',
          team_id: null,
          url: 'https://digitalai.atlassian.net',
          user: 'test1@atlassian.net',
        },
        {
          id: '222222222222222222222222',
          title: 'Jira Server 2',
          improve_types: '',
          isdefault: false,
          maintain_types: '',
          name: 'Configuration/Custom/Configuration2222',
          password: '',
          team_id: null,
          url: 'https://digitalai.atlassian.net',
          user: 'test2@atlassian.net',
        },
      ],
    },
    {
      id: '343434343434344',
      title: 'V1plugin',
      servers: [
        {
          id: '333333333333333333333331',
          title: 'v1 Server1',
          isdefault: true,
          name: '',
          token: '',
          url: 'www7.v1host.com',
        },
        {
          id: '333333333333333333333332',
          title: 'v1 Server2',
          isdefault: false,
          name: '',
          token: '',
          url: 'www7.v1host.com',
        },
      ],
    },
  ],
};
