name: Branch Protection Switch

on:
  workflow_dispatch:

jobs:
  protection:
    name: Branch Protection
    runs-on: ubuntu-latest

    steps:
      # https://github.community/t/branch-protection-api-returning-404/217405
      # https://docs.github.com/en/rest/reference/branches#update-branch-protection
      - name: Get existing branch protection
        id: get_branch_protection
        uses: octokit/request-action@v2.0.24
        with:
          route: GET /repos/digital-ai/dot-components/branches/develop/protection
          mediaType: |
            format: application/json
        env:
          GITHUB_TOKEN: ${{ secrets.DIGITALAI_BOT_TOKEN }}

      # - run: echo ${{steps.get_branch_protection.outputs.data}}

      - name: Branch protection OFF
        uses: octokit/request-action@v2.0.24
        with:
          route: PUT /repos/digital-ai/dot-components/branches/develop/protection
          mediaType: |
            format: application/json
          required_status_checks: |
            null
          required_pull_request_reviews: |
            null
          enforce_admins: |
            null
          required_conversation_resolution: |
            null
          restrictions: |
            null
        env:
          GITHUB_TOKEN: ${{ secrets.DIGITALAI_BOT_TOKEN }}

      - name: Branch protection ON
        uses: octokit/request-action@v2.0.24
        with:
          route: PUT /repos/digital-ai/dot-components/branches/develop/protection
          mediaType: |
            format: application/json
          required_status_checks: |
            strict: false
            checks:
              - context: "Lint & Build"
              - context: "Run Unit Tests"
              - context: "Run E2E Tests"
          enforce_admins: |
            false
          required_pull_request_reviews: |
            required_approving_review_count: 1
          required_conversation_resolution: |
            true
          restrictions: |
            null
        env:
          GITHUB_TOKEN: ${{ secrets.DIGITALAI_BOT_TOKEN }}
