name: Generate Changelog

on:
  workflow_dispatch:

jobs:
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v0.8.0
        with:
          # Optional, you can provide any name for your changelog file,
          # defaults to `CHANGELOG.md` if not provided.
          changelog_filename: CI_CHANGELOG.md
          # Optional, only required when you want more customization
          # e.g: group your changelog by labels with custom titles,
          # different version prefix, pull request title and version number regex etc.
          # config file can be in JSON or YAML format.
          config_file: changelog-ci-config.yml
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
