name: Test Changelog Generation

on:
  workflow_dispatch:
  # pull_request:

jobs:
  # https://github.com/faberNovel/github-changelog-generator-action
  generate:
    name: Generate Changelog
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate changelog
        uses: fabernovel/github-changelog-generator-action@master
        with:
          # https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples#additional-options
          options: --token ${{ secrets.GITHUB_TOKEN }} --date-format %m/%d/%Y --output CI_CHANGE_LOG.md --enhancement-label **Features:** --enhancement-labels enhancement --bug-labels defect --exclude-tags 0.0.0-alpha.0.0.1-s73861automateversioning.995.d3186ab

      # https://github.com/marketplace/actions/add-commit
      - name: Commit and Push Changelog
        uses: EndBug/add-and-commit@master
        with:
          add: CI_CHANGE_LOG.md --force
          default_author: github_actions
          message: 'Update Changelog'
