name: Lint, Test & Build

on:
  workflow_dispatch:

jobs:
  setup:
    name: Setup & Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache yarn dependencies
        uses: c-hive/gha-yarn-cache@v1

      - name: yarn install
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

  verification:
    name: Lint & Format
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
      - name: yarn lint
        run: yarn lint

      - name: yarn format
        run: yarn format:check

  build:
    name: Build
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
      - name: yarn build
        run: yarn build
        env:
          CI: true

  test:
    name: Run Tests
    needs: [setup]
    runs-on: ubuntu-latest

    steps:
      - name: run unit tests
        run: yarn test
        env:
          CI: true

      - name: run e2e tests
        run: yarn e2e:ci
        env:
          CI: true
