name: Lint, Test & Build

on:
  workflow_dispatch:

jobs:
  verification:
    name: Lint, Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache yarn dependencies
        uses: c-hive/gha-yarn-cache@latest

      # - name: Get yarn cache directory path
      #   id: yarn-cache-dir-path
      #   run: echo "::set-output name=dir::$(yarn cache dir)"

      # - name: yarn cache
      #   uses: actions/cache@v2
      #   id: yarn-cache
      #   with:
      #     path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
      #     key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
      #     restore-keys: |
      #       ${{ runner.os }}-yarn-

      - name: yarn install
        # if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: yarn lint
        run: yarn lint

      - name: Code Format
        run: |
          if [[ $GITHUB_BASE_REF ]]
          then
            export NX_BASE=remotes/origin/$GITHUB_BASE_REF
          else
            export NX_BASE=$(git rev-parse HEAD~1)
          fi
          echo "Base => $NX_BASE"
          yarn format:check --base=$NX_BASE

      - name: yarn build
        run: yarn build
        env:
          CI: true

      - name: run unit tests
        run: yarn test
        env:
          CI: true

      - name: run e2e tests
        run: yarn e2e:ci
        env:
          CI: true
