name: Continuous Release

# Paths are now supported by GitHub on ALL workflows
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
on:
  push:
    paths:
      - .github/workflows/version.yml
      - libs/dot-components/src/**
    branches:
      - master

jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}
          # ref: ${{ github.head_ref }} # checkout the correct branch name
          # fetch-depth: 0 # fetch the whole repo history

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v1'
        with:
          node-version: 12

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PACKAGEJSON_DIR: 'libs/dot-components'
        with:
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
          default: prerelease
          major-wording: 'MAJOR'
          minor-wording: 'minor'
          patch-wording: 'patch'
          tag-prefix: ''
          target-branch: 'master'

      - name: 'cat package.json'
        run: cat ./package.json

      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

  # git-version:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     version: ${{ steps.git_version.outputs.VERSION }}

  #     # currently there is an issue updating the version
  #     # https://github.com/codacy/git-version/issues/48
  #     - name: Git Version
  #       id: git_version
  #       uses: codacy/git-version@2.4.0
  #       with:
  #         # The name of the release branch
  #         release-branch: master
  #         # The prefix to use in the version
  #         prefix: alpha-
  #         # The paths to be used to calculate changes (comma-separated)
  #         log-paths: libs/dot-components/src/

  # create-tag:
  #   needs: [git-version, modify-pkg-json]
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout Code
  #       uses: actions/checkout@v2

  #     - name: Create Tag
  #       uses: negz/create-tag@v1
  #       with:
  #         version: ${{needs.git-version.outputs.version}}
  #         message: 'Tag with version ${{needs.git-version.outputs.version}}'
  #         token: ${{ github.token }}

  # release package
  # https://github.com/elgohr/Github-Release-Action

  # deploy package to npm
  # https://github.com/marketplace/actions/npm-publish

  # deploy to storybook (build.yml)
  # OR repository-dispatch may be able to trigger a separate workflow
  # https://github.com/peter-evans/repository-dispatch
