name: Continuous Release

# Paths are now supported by GitHub on ALL workflows
# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
on:
  push:
    paths:
      - .github/workflows/version.yml
      - libs/dot-components/src/**
    branches:
      - master

jobs:
  bump-version:
    name: 'Bump Version on master'
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout code'
        uses: 'actions/checkout@v2'
        with:
          ref: ${{ github.ref }}

      - name: 'cat libs/dot-components/package.json'
        run: cat ./libs/dot-components/package.json

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@v1'
        with:
          node-version: 12

      - name: 'Automated Version Bump'
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        env:
          GITHUB_TOKEN: ${{ github.token }}
          # PACKAGEJSON_DIR: 'libs/dot-components'
        with:
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
          default: prerelease
          major-wording: 'MAJOR'
          minor-wording: 'minor'
          patch-wording: 'patch'
          tag-prefix: ''
          target-branch: 'master'
          preid: 'alpha'

      - name: 'cat libs/dot-components/package.json'
        run: cat ./libs/dot-components/package.json

      - name: 'Output Step'
        env:
          NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
        run: echo "new tag $NEW_TAG"

  # release package
  # https://github.com/elgohr/Github-Release-Action
  # https://github.com/marvinpinto/action-automatic-releases
  # https://github.com/softprops/action-gh-release
  # https://github.com/ncipollo/release-action

  # deploy package to npm
  # https://github.com/marketplace/actions/npm-publish

  # deploy to storybook (build.yml)
  # OR repository-dispatch may be able to trigger a separate workflow
  # https://github.com/peter-evans/repository-dispatch
