name: Continuous Release

on:
  push:
    paths:
      - libs/dot-components/src/**
      - libs/dot-components/package.json
      - .github/workflows/**
    branches:
      - master

jobs:
  # https://github.com/benc-uk/workflow-dispatch
  verification:
    name: Trigger - Lint, Test & Build
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          inputs: '{"ref": "${{ github.sha }}"}'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow: Lint, Test & Build

  # https://github.com/lewagon/wait-on-check-action
  checks:
    name: Wait on "Lint, Test & Build" Workflow
    runs-on: ubuntu-latest
    needs: [verification]

    steps:
      - name: wait on build
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.sha }}
          check-name: Lint & Build
          repo-token: ${{ github.token }}
          wait-interval: 20

      - name: wait on unit tests
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.sha }}
          check-name: Run Unit Tests
          repo-token: ${{ github.token }}
          wait-interval: 20

      - name: wait on e2e tests
        uses: lewagon/wait-on-check-action@master
        with:
          ref: ${{ github.sha }}
          check-name: Run E2E Tests
          repo-token: ${{ github.token }}
          wait-interval: 20

  # https://github.com/marketplace/actions/automated-version-bump
  bump-version:
    name: Bump Version & Create GitHub Tag
    runs-on: ubuntu-latest
    needs: [checks]
    outputs:
      new-version: ${{ steps.version-bump.outputs.newTag }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Automated Version Bump
        id: version-bump
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ github.token }}
          PACKAGEJSON_DIR: 'libs/dot-components'
        with:
          commit-message: 'CI: bumps version to {{version}} [skip ci]'
          # default: prerelease
          major-wording: 'MAJOR'
          minor-wording: 'minor'
          # Providing patch-wording will prevent every commit triggering patch bump.
          # patch-wording: 'patch'
          rc-wording: 'alpha, RELEASE, BETA'
          target-branch: 'master'
          # rc-wording will override the preid
          preid: 'alpha'
          tag-prefix: 'alpha'

  # https://github.com/faberNovel/github-changelog-generator-action
  changelog:
    name: Generate Changelog
    runs-on: ubuntu-latest
    needs: [bump-version]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Changelog
        uses: fabernovel/github-changelog-generator-action@master
        with:
          # https://github.com/github-changelog-generator/github-changelog-generator/wiki/Advanced-change-log-generation-examples#additional-options
          options: --token ${{ secrets.GITHUB_TOKEN }} --date-format %m/%d/%Y --output CI_CHANGE_LOG.md --enhancement-label **Features:** --enhancement-labels enhancement --bug-labels defect --exclude-tags 0.0.0-alpha.0.0.1-s73861automateversioning.995.d3186ab

      # https://github.com/marketplace/actions/add-commit
      - name: Commit and Push Changelog
        uses: EndBug/add-and-commit@master
        with:
          add: CI_CHANGE_LOG.md
          default_author: github_actions
          message: 'Update Changelog'

  # https://github.com/marvinpinto/action-automatic-releases
  create-release:
    name: Create GitHub Release
    runs-on: ubuntu-latest
    needs: [bump-version, changelog]
    if: needs.bump-version.outputs.new-version != ''

    steps:
      - name: New Version
        env:
          NEW_VERSION: ${{ steps.bump-version.outputs.new-version }}
        run: echo "new version $NEW_VERSION"

      - name: Create Release
        id: create-release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          automatic_release_tag: ${{needs.bump-version.outputs.new-version}}
          repo_token: ${{ github.token }}
          prerelease: true

  # https://github.com/benc-uk/workflow-dispatch
  release:
    name: Trigger - Deploy to NPM
    runs-on: ubuntu-latest
    needs: [create-release]

    steps:
      - name: Trigger Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          inputs: '{"ref": "${{ github.ref }}"}'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow: Deploy to NPM

  # https://github.com/benc-uk/workflow-dispatch
  github-pages:
    name: Trigger - Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: [create-release]

    steps:
      - name: Trigger Workflow
        uses: benc-uk/workflow-dispatch@v1
        with:
          inputs: '{"ref": "${{ github.ref }}"}'
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          workflow: Deploy to GitHub Pages
